import type { User } from "@/entities/user";

export const initialUsers: User[] = [
  {
    id: "1",
    name: "Иван Петров",
    email: "ivan.petrov@example.com",
    role: "admin",
    status: "active",
    createdAt: "2024-01-15T10:30:00Z",
  },
  {
    id: "2",
    name: "Анна Смирнова",
    email: "anna.smirnova@example.com",
    role: "user",
    status: "active",
    createdAt: "2024-02-03T14:12:00Z",
  },
  {
    id: "3",
    name: "Дмитрий Кузнецов",
    email: "d.kuznetsov@example.com",
    role: "user",
    status: "inactive",
    createdAt: "2023-11-20T08:45:00Z",
  },
  {
    id: "4",
    name: "Мария Иванова",
    email: "m.ivanova@example.com",
    role: "admin",
    status: "inactive",
    createdAt: "2023-09-01T18:00:00Z",
  },
  {
    id: "5",
    name: "Алексей Морозов",
    email: "alexey.morozov@example.com",
    role: "user",
    status: "active",
    createdAt: "2024-03-10T09:20:00Z",
  },
  {
    id: "6",
    name: "Екатерина Волкова",
    email: "e.volkova@example.com",
    role: "user",
    status: "active",
    createdAt: "2024-01-28T16:40:00Z",
  },
  {
    id: "7",
    name: "Сергей Новиков",
    email: "s.novikov@example.com",
    role: "admin",
    status: "active",
    createdAt: "2023-12-05T11:05:00Z",
  },
  {
    id: "8",
    name: "Ольга Фёдорова",
    email: "olga.fedorova@example.com",
    role: "user",
    status: "inactive",
    createdAt: "2023-08-17T07:55:00Z",
  },
  {
    id: "9",
    name: "Никита Соколов",
    email: "nikita.sokolov@example.com",
    role: "user",
    status: "active",
    createdAt: "2024-02-20T19:10:00Z",
  },
  {
    id: "10",
    name: "Татьяна Орлова",
    email: "t.orlova@example.com",
    role: "admin",
    status: "inactive",
    createdAt: "2023-10-30T13:25:00Z",
  },
];
